### ISSUE TITLE
Compilation failiure on windows

### ISSUE THREAD

**Issue by Spooky-Firefox** [perlindgren/syncrim#79]
When running `cargo run` it returns with error
```
error: could not compile `eframe` (lib) due to 2 previous errors
```
The cause seem to be unresolved import, winapi winuser.
Version `0.26.2` of Egui seem to have fixed the problem, https://github.com/emilk/egui/releases/tag/0.26.2

Current workaround is to add winapi to cargo toml
```
winapi = { version = "0.3.9", features = ["winuser"] }
```

**Comment by perlindgren** [comment]
Did you try updating to 0.26.2?

**Comment by perlindgren** [comment]
As I recall Pawel tried bumping version a while back, but ran into problem that the canvas did not get focus in the editor, thus you could not scroll around. Maybe this problem has been fixed by later versions (if it was a bug) I don't know, or maybe the API has changed so that we are currently missing something.

**Comment by perlindgren** [comment]
(In general, we should to stick to the latest...)

**Comment by onsdagens** [comment]
let's do with the workaround for now, do you mind opening a PR for it? i'll keep the issue open until we've bumped `egui`

**Comment by onsdagens** [comment]
we should also look into adding windows and macos runners to the CI
